<a href="https://colab.research.google.com/github/ash030889/Machine-Learning/blob/main/tensorflow_practice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)
import numpy as np
import matplotlib.pyplot as plt


TensorFlow version: 2.15.0


In [7]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [8]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [9]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.614316  ,  0.8113788 , -0.13627765, -0.11579528, -0.33714524,
         0.0706005 ,  0.26045066, -0.14237645, -0.35751665, -0.25149146]],
      dtype=float32)

In [10]:
tf.nn.softmax(predictions).numpy()

array([[0.16369797, 0.19935474, 0.07727956, 0.07887875, 0.06321628,
        0.09504092, 0.11491098, 0.07680967, 0.0619415 , 0.06886965]],
      dtype=float32)

In [11]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [12]:
loss_fn(y_train[:1], predictions).numpy()

2.3534477

In [13]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [14]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.2935 - accuracy: 0.9163
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1404 - accuracy: 0.9582
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1058 - accuracy: 0.9679
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0883 - accuracy: 0.9722
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0751 - accuracy: 0.9766


In [15]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0731 - accuracy: 0.9777 - 568ms/epoch - 2ms/step


[0.07310887426137924, 0.9776999950408936]

In [16]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [17]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.18099006e-08, 4.64512162e-09, 9.87880412e-07, 3.08369141e-04,
        2.65721234e-12, 2.24650739e-06, 1.07454757e-11, 9.99683619e-01,
        3.18794235e-07, 4.49603885e-06],
       [5.52847823e-10, 1.39110598e-05, 9.99981523e-01, 4.51885307e-06,
        2.76481708e-18, 1.81052506e-08, 5.67322189e-10, 1.16028105e-13,
        1.54897268e-08, 2.18597858e-14],
       [1.06450258e-07, 9.99328613e-01, 1.16436691e-04, 1.07330097e-05,
        7.97301909e-05, 7.15469832e-06, 1.40803095e-04, 1.77971262e-04,
        1.34790200e-04, 3.64617881e-06],
       [9.99939799e-01, 4.59683180e-10, 1.72642067e-05, 3.35821881e-07,
        4.25377955e-08, 1.96166684e-06, 2.17724682e-05, 1.08524034e-07,
        9.40758866e-08, 1.87304340e-05],
       [2.47221828e-06, 1.88431493e-09, 6.95256449e-06, 1.39018141e-06,
        9.90313053e-01, 1.15146861e-07, 4.14491160e-06, 1.74211906e-04,
        2.92010009e-06, 9.49474890e-03]], dtype=float32)>